
const STORAGE_KEY="objectif85-v2";let selectedDate=new Date();
const defaults={age:48,height:185,currentWeight:93,targetWeight:85,sessions:4,equipment:"Haltères et poids du corps",forbidden:"Porc",budget:""};
function keyFor(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function load(){return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"days":{},"shopping":{},"settings":{}}')}
function save(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function getDay(d=selectedDate){const s=load();return s.days[keyFor(d)]||{meals:{},sports:{},weight:"",waist:"",steps:"",water:"",protein:"",sleep:""}}
function setDay(data,d=selectedDate){const s=load();s.days[keyFor(d)]=data;save(s)}
function cycleIndex(d){const start=new Date(2026,0,1);const n=Math.floor((new Date(d.getFullYear(),d.getMonth(),d.getDate())-start)/86400000);return((n%28)+28)%28}
function weekDates(d){const x=new Date(d),shift=(x.getDay()+6)%7;x.setDate(x.getDate()-shift);return Array.from({length:7},(_,i)=>{const y=new Date(x);y.setDate(x.getDate()+i);return y})}
function completion(d){const x=getDay(d),total=4+(WORKOUT_PLAN[d.getDay()]||[]).length,done=Object.values(x.meals||{}).filter(Boolean).length+Object.values(x.sports||{}).filter(Boolean).length;return total?Math.round(done/total*100):0}
function renderWeek(){const r=document.getElementById("weekStrip");r.innerHTML="";weekDates(selectedDate).forEach(d=>{const b=document.createElement("button");b.className="day-chip"+(keyFor(d)===keyFor(selectedDate)?" active":"");const sc=completion(d);b.innerHTML=`<span>${d.toLocaleDateString("fr-FR",{weekday:"short"}).replace(".","").toUpperCase()}</span><strong>${d.getDate()}</strong><i style="background:${sc===100?"#52b85a":sc>0?"#ff8a27":"#697482"}"></i>`;b.onclick=()=>{selectedDate=d;renderToday()};r.appendChild(b)})}
function renderToday(){renderWeek();const idx=cycleIndex(selectedDate),data=getDay(),names=["Petit-déjeuner","Déjeuner","Collation","Dîner"],icons=["☀","🍗","🥛","🐟"];document.getElementById("cycleLabel").textContent=`JOUR ${idx+1} / 28`;const dl=selectedDate.toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"});document.getElementById("dateLabel").textContent=dl[0].toUpperCase()+dl.slice(1);document.getElementById("dayScore").textContent=completion(selectedDate)+"%";
const meals=document.getElementById("mealList");meals.innerHTML="";MEAL_PLAN[idx].forEach((m,i)=>{const row=document.createElement("div");row.className="meal-card";row.innerHTML=`<div class="icon-box">${icons[i]}</div><div><h3>${names[i]}</h3><p>${m}</p></div><button class="check-btn ${data.meals[i]?"done":""}">${data.meals[i]?"✓":""}</button>`;row.querySelector("button").onclick=()=>{const d=getDay();d.meals[i]=!d.meals[i];setDay(d);renderToday()};meals.appendChild(row)});
const sport=document.getElementById("sportList");sport.innerHTML="";(WORKOUT_PLAN[selectedDate.getDay()]||[]).forEach((t,i)=>{const p=t.split("—"),row=document.createElement("div");row.className="task-row";row.innerHTML=`<div class="icon-box">${i===0?"🚶":"🏋"}</div><div><h3>${p[0].trim()}</h3><p>${p[1]?p[1].trim():""}</p></div><button class="check-btn ${data.sports[i]?"done":""}">${data.sports[i]?"✓":""}</button>`;row.querySelector("button").onclick=()=>{const d=getDay();d.sports[i]=!d.sports[i];setDay(d);renderToday()};sport.appendChild(row)})}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.nav===id));document.getElementById("pageTitle").textContent={todayPage:"Aujourd’hui",trackingPage:"Suivi",shoppingPage:"Courses",settingsPage:"Paramètres"}[id];if(id==="trackingPage")renderTracking();if(id==="shoppingPage")renderShopping();if(id==="settingsPage")renderSettings();scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>showPage(b.dataset.nav));document.getElementById("todayBtn").onclick=()=>{selectedDate=new Date();showPage("todayPage");renderToday()};
const trackFields=[["weight","Poids (kg)","0.1"],["waist","Tour de taille (cm)","0.1"],["steps","Pas","1"],["water","Eau (L)","0.1"],["protein","Protéines (g)","1"],["sleep","Sommeil (h)","0.25"]];
function renderTracking(){const d=getDay(),f=document.getElementById("trackingForm");f.innerHTML="";trackFields.forEach(([k,l,s])=>{const x=document.createElement("div");x.className="field";x.innerHTML=`<label>${l}</label><input type="number" step="${s}" data-key="${k}" value="${d[k]||""}">`;f.appendChild(x)});updateSummary()}
document.getElementById("saveTracking").onclick=()=>{const d=getDay();document.querySelectorAll("#trackingForm input").forEach(i=>d[i.dataset.key]=i.value);setDay(d);updateSummary()};
function history(){return Object.entries(load().days||{}).map(([date,d])=>({date,...d})).sort((a,b)=>a.date.localeCompare(b.date))}
function drawChart(id,vals,color){const svg=document.getElementById(id);svg.innerHTML="";const w=360,h=170,p=24,v=vals.length?vals:[0],min=Math.min(...v),max=Math.max(...v),r=max-min||1;for(let i=0;i<4;i++){const y=p+i*((h-p*2)/3);svg.insertAdjacentHTML("beforeend",`<line x1="${p}" y1="${y}" x2="${w-p}" y2="${y}" stroke="#27313b"/>`)}const pts=v.map((n,i)=>[v.length===1?w/2:p+i*((w-p*2)/(v.length-1)),h-p-((n-min)/r)*(h-p*2)]);if(pts.length>1)svg.insertAdjacentHTML("beforeend",`<polyline fill="none" stroke="${color}" stroke-width="4" points="${pts.map(x=>x.join(",")).join(" ")}"/>`);pts.forEach(([x,y])=>svg.insertAdjacentHTML("beforeend",`<circle cx="${x}" cy="${y}" r="5" fill="#0e1319" stroke="${color}" stroke-width="3"/>`))}
function updateSummary(){const h=history(),s={...defaults,...(load().settings||{})},weights=h.filter(x=>x.weight).map(x=>Number(x.weight)),waists=h.filter(x=>x.waist).map(x=>Number(x.waist));document.getElementById("currentWeight").textContent=(weights.at(-1)||s.currentWeight)+" kg";document.getElementById("currentWaist").textContent=(waists.at(-1)||97)+" cm";document.getElementById("successDays").textContent=Object.keys(load().days||{}).filter(k=>completion(new Date(k+"T12:00:00"))===100).length;document.getElementById("weightTrend").textContent=weights.length>1?`${(weights.at(-1)-weights[0]).toFixed(1)} kg`:"0 kg";document.getElementById("waistTrend").textContent=waists.length>1?`${(waists.at(-1)-waists[0]).toFixed(1)} cm`:"0 cm";drawChart("weightChart",weights,"#e8b85e");drawChart("waistChart",waists,"#ff7028")}
function renderShopping(){const state=load(),checked=state.shopping||{},cats=document.getElementById("shoppingCategories"),bought=document.getElementById("boughtList");cats.innerHTML="";bought.innerHTML="";let total=0,done=0;Object.entries(SHOPPING_LIST).forEach(([cat,items])=>{const box=document.createElement("section");box.className="shopping-category";box.innerHTML=`<h3>${cat}</h3><div class="shopping-list"></div>`;const list=box.querySelector(".shopping-list");items.forEach(item=>{total++;const id=cat+"::"+item,isDone=!!checked[id];if(isDone)done++;const row=document.createElement("div");row.className="shopping-item"+(isDone?" done":"");row.innerHTML=`<input type="checkbox" ${isDone?"checked":""}><label>${item}</label>`;row.querySelector("input").onchange=e=>{const s=load();s.shopping=s.shopping||{};s.shopping[id]=e.target.checked;save(s);renderShopping()};(isDone?bought:list).appendChild(row)});if(list.children.length)cats.appendChild(box)});if(!bought.children.length)bought.innerHTML='<p class="muted">Aucun article acheté pour le moment.</p>';const pct=total?Math.round(done/total*100):0;document.getElementById("shoppingScore").textContent=pct+"%";document.getElementById("shoppingProgress").style.width=pct+"%"}
document.getElementById("resetShopping").onclick=()=>{if(confirm("Réinitialiser toute la liste de courses ?")){const s=load();s.shopping={};save(s);renderShopping()}};
const settingFields=[["age","Âge","number"],["height","Taille (cm)","number"],["currentWeight","Poids actuel (kg)","number"],["targetWeight","Poids cible (kg)","number"],["sessions","Séances par semaine","number"],["equipment","Matériel disponible","text"],["forbidden","Aliments interdits","text"],["budget","Budget mensuel (€)","number"]];
function renderSettings(){const s={...defaults,...(load().settings||{})},r=document.getElementById("settingsForm");r.innerHTML="";settingFields.forEach(([k,l,t])=>{const f=document.createElement("div");f.className="field";f.innerHTML=`<label>${l}</label><input data-key="${k}" type="${t}" value="${s[k]||""}">`;r.appendChild(f)})}
document.getElementById("saveSettings").onclick=()=>{const s=load();s.settings=s.settings||{};document.querySelectorAll("#settingsForm input").forEach(i=>s.settings[i.dataset.key]=i.type==="number"?Number(i.value):i.value);save(s);alert("Paramètres enregistrés.")};
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
renderToday();
